name = "Xfoil"
uuid = "19641d66-a62d-11e8-2441-8f57a969a9c4"
authors = ["Taylor McDonnell <taylor.golden.mcdonnell@gmail.com>"]
version = "0.3.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
